# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QTGvoorGeotechniekDialog
                                 A QGIS plugin
  QTG voor Geonius Geotechniek B.V.
  This plugin contains tools for employees of Geonius Geotechniek
  Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-02-10
        git sha              : $Format:%H$
        copyright            : (C) 2019 Geonius Geotechniek B.V.
        email                : q.vanmoerbeke@geonius.nl
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
from qgis.core import *
from qgis.gui import *
from qgis.utils import *

from PyQt5 import uic
from PyQt5 import QtWidgets
from PyQt5.QtWidgets import QAction, QInputDialog, QLineEdit, QFileDialog, QWidget, QVBoxLayout, QCheckBox, QMessageBox

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'ExportCSV_dialog.ui'))

class ExportCSV_dialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(ExportCSV_dialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        # Titel
        self.setWindowTitle('Selectie export CSV')

